# XPX_Bridge.rb
# Auto-generated by XPX Engine. Do not edit manually.
# This script loads XPX JSON data and bridges it to mkxp-z runtime.

require 'json'

module XPX
  DATA_DIR = File.join(File.dirname(__FILE__), '..', 'Data')

  # Try .xpxdata first, fall back to .json. Phase 3 of the native
  # xpxdata runtime renamed sidecars to .xpxdata for branding
  # consistency; this lookup keeps loading projects that haven't
  # been re-saved since the rename. The caller passes the historical
  # .json name; we strip the extension and try both.
  def self.load_json(filename)
    base = filename.sub(/\.(?:json|xpxdata)$/i, "")
    [base + ".xpxdata", base + ".json"].each do |name|
      path = File.join(DATA_DIR, name)
      next unless File.exist?(path)
      return JSON.parse(File.read(path, encoding: 'utf-8'))
    end
    nil
  end

  def self.boot
    load_system
    load_tilesets
    load_common_events
    load_scripts
  end

  def self.load_system
    data = load_json('XPX_System.xpxdata')
    return unless data
    $data_system = RPG::System.new rescue OpenStruct.new
    $data_system.game_title   = data['game_title']
    $data_system.switches     = data['switches'].map { |s| s['name'] }
    $data_system.variables    = data['variables'].map { |v| v['name'] }
  end

  def self.load_tilesets
    # Placeholder: when a pure-XPX runtime (no Legacy, no Scripts.rxdata)
    # is built, this will need to populate $data_tilesets from scratch from
    # XPX_Tilesets.xpxdata including all the per-tile metadata arrays.
    # For now XPX projects always run hosted by Legacy, and
    # XPX_Preload.rb applies the metadata overrides after Tilesets.rxdata
    # loads. Keep this method as a stub so XPX_Bridge.rb's boot
    # sequence doesn't error.
    data = load_json('XPX_Tilesets.xpxdata')
    return unless data
    $data_tilesets ||= { nil => nil }
    data.each do |ts|
      t = RPG::Tileset.new rescue OpenStruct.new
      t.id             = ts['id']
      t.name           = ts['name']
      t.tileset_name   = ts['tileset_name']
      t.autotile_names = ts['autotile_names'] || []
      $data_tilesets[t.id] = t unless $data_tilesets.key?(t.id)
    end
  end

  def self.load_common_events
    data = load_json('XPX_CommonEvents.json')
    return unless data
    $data_common_events = { nil => nil }
    data.each do |ce|
      c = RPG::CommonEvent.new rescue OpenStruct.new
      c.id        = ce['id']
      c.name      = ce['name']
      c.trigger   = ce['trigger']
      c.switch_id = ce['switch_id']
      c.list      = build_command_list(ce['list'] || [])
      $data_common_events[c.id] = c
    end
  end

  def self.load_scripts
    data = load_json('XPX_Scripts.json')
    return unless data
    data.each do |script|
      next unless script['language'] == 'Ruby'
      begin
        eval(script['code'])
      rescue => e
        puts "XPX Script '#{script['name']}' error: #{e.message}"
      end
    end
  end

  def self.build_command_list(list)
    list.map do |cmd|
      c = RPG::EventCommand.new rescue OpenStruct.new(code: 0, indent: 0, parameters: [])
      c.code       = cmd['code']
      c.indent     = cmd['indent'] || 0
      c.parameters = cmd['parameters'] || []
      c
    end
  end
end

# Boot the bridge
XPX.boot
